"""Checkpointed weekday Agmarknet scraper for Tamil Nadu, 2010-01-01..2026-06-30.
The supplied agmarknet_tn_2010_2025.csv is external and is not generated by this scraper.
Set AGMARKNET_CODES as JSON or comma-separated name:code pairs before use.
"""
import json,os,time
from datetime import date,timedelta
import requests,pandas as pd
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
from bs4 import BeautifulSoup
from agrisight_common import RAW,COMMODITIES
URL=os.getenv('AGMARKNET_URL','https://agmarknet.gov.in/SearchCmmMkt.aspx')
def codes():
 raw=os.getenv('AGMARKNET_CODES','')
 if not raw: raise SystemExit('Set AGMARKNET_CODES to current Agmarknet commodity codes before scraping.')
 try: result=json.loads(raw)
 except json.JSONDecodeError: result=dict(x.split(':',1) for x in raw.split(',') if ':' in x)
 result={str(k).strip().title():str(v).strip() for k,v in result.items()}
 missing=set(COMMODITIES)-set(result)
 if missing: raise SystemExit('Missing Agmarknet codes for: '+', '.join(sorted(missing)))
 return result
def extract(html,day,commodity):
 soup=BeautifulSoup(html,'html.parser'); table=soup.find(id='cphBody_GridPriceData')
 if table is None: return []
 heads=[x.get_text(' ',strip=True).lower() for x in table.select('tr th')]
 rows=[]
 for tr in table.select('tr'):
  cells=[x.get_text(' ',strip=True) for x in tr.select('td')]
  if not cells or 'koyambedu' not in ' '.join(cells).lower(): continue
  values={}
  for i,h in enumerate(heads):
   if i<len(cells): values[h]=cells[i]
  def find(*tokens):
   return next((v for k,v in values.items() if any(t in k for t in tokens)),None)
  nums=[]
  for tokens in (('min price','minimum price'),('max price','maximum price'),('modal price','modal')):
   value=find(*tokens); nums.append(pd.to_numeric(str(value or '').replace(',',''),errors='coerce'))
  if all(pd.isna(v) for v in nums): nums=[pd.to_numeric(x.replace(',',''),errors='coerce') for x in cells[-3:]]
  rows.append(dict(arrival_date=day,state='Tamil Nadu',district='Chennai',market='Koyambedu',commodity=commodity,min_price=nums[0],max_price=nums[1],modal_price=nums[2]))
 return rows
def main():
 codes_by_name=codes(); cp=RAW/'agmarknet_checkpoint.txt'; out=RAW/'agmarknet_koyambedu_raw.csv'
 start=date(2010,1,1)
 if cp.exists():
  try: start=date.fromisoformat(cp.read_text(encoding='utf-8').strip())+timedelta(days=1)
  except ValueError: raise SystemExit(f'Invalid checkpoint: {cp}')
 end=date(2026,6,30); batch=[]; session=requests.Session(); session.mount('https://',HTTPAdapter(max_retries=Retry(total=3,backoff_factor=.7,status_forcelist=(429,500,502,503,504),allowed_methods=('GET',)))); session.headers.update({'User-Agent':os.getenv('AGMARKNET_USER_AGENT','Mozilla/5.0 (compatible; AgriSightPOC/1.0)' )})
 days=0
 while start<=end:
  current=start
  failed=False
  if current.weekday()<6:
   for commodity in COMMODITIES:
    params={'Tx_Commodity':codes_by_name[commodity],'Tx_State':'33','Tx_Date':current.strftime('%d-%b-%Y'),'Tx_Market':'0','Tx_Trend':'0'}
    try:
     response=session.get(URL,params=params,timeout=35); response.raise_for_status(); batch.extend(extract(response.text,current,commodity))
    except requests.RequestException as exc: print(f'WARN {current} {commodity}: {exc}'); failed=True
    time.sleep(float(os.getenv('AGMARKNET_DELAY_SECONDS','.25')))
  days+=1
  if failed:
   if batch:
    new=pd.DataFrame(batch); old=pd.read_csv(out) if out.exists() else pd.DataFrame()
    pd.concat([old,new],ignore_index=True).drop_duplicates(['arrival_date','commodity','market']).to_csv(out,index=False)
   cp.write_text((current-timedelta(days=1)).isoformat(),encoding='utf-8')
   raise SystemExit(f'Incomplete requests on {current}; checkpoint left before that date. Re-run to retry it.')
  if days%30==0 or current==end:
   if batch:
    new=pd.DataFrame(batch)
    if out.exists(): new=pd.concat([pd.read_csv(out),new],ignore_index=True).drop_duplicates(['arrival_date','commodity','market'])
    new.to_csv(out,index=False); batch=[]
   cp.write_text(current.isoformat(),encoding='utf-8'); print(f'Checkpoint {current}')
  start=current+timedelta(days=1)
 if batch:
  new=pd.DataFrame(batch); old=pd.read_csv(out) if out.exists() else pd.DataFrame()
  pd.concat([old,new],ignore_index=True).drop_duplicates(['arrival_date','commodity','market']).to_csv(out,index=False)
 if out.exists(): pd.read_csv(out).to_parquet(RAW/'agmarknet_koyambedu_raw.parquet',index=False)
 print('Finished. The supplied agmarknet_tn_2010_2025.csv is an external dataset, not scraper output.')
if __name__=='__main__': main()
